# Generated by Django 4.0.3 on 2022-04-14 14:57

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('author', models.CharField(max_length=16)),
                ('category', models.CharField(choices=[('other', 'Inne')], max_length=24)),
                ('country', models.CharField(choices=[('poland', 'Polska')], max_length=32)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publish',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
