# Generated by Django 3.2.13 on 2022-07-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='slug',
        ),
        migrations.AddField(
            model_name='guide',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='slug_url',
            field=models.SlugField(default='', editable=False),
            preserve_default=False,
        ),
    ]
