# Generated by Django 3.2.13 on 2022-05-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='object_id',
            field=models.SlugField(blank=True, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
