# Generated by Django 4.0.3 on 2022-04-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guide',
            managers=[
            ],
        ),
    ]
