# Generated by Django 4.0.3 on 2022-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0002_alter_guide_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='id',
        ),
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('other', 'Inne'), ('hotels', 'Hotele')], max_length=24),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
