# Generated by Django 3.2.13 on 2022-07-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0003_auto_20220717_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='travel_guides.country'),
        ),
    ]
