# Generated by Django 3.2.13 on 2022-05-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0003_remove_guide_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='object_id',
        ),
        migrations.AddField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
