# Generated by Django 3.2.13 on 2022-07-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0004_auto_20220717_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
