# Generated by Django 3.2.13 on 2022-05-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_guides', '0005_alter_guide_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='visible',
            field=models.CharField(choices=[('visible', 'Widoczne'), ('Hidden', 'Ukryty')], default='visible', max_length=16),
        ),
    ]
