# Generated by Django 4.0.3 on 2022-04-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='link',
            field=models.URLField(default='emptyUrl'),
            preserve_default=False,
        ),
    ]
