# Generated by Django 4.0.3 on 2022-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='shortContent',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
