# Generated by Django 4.0.3 on 2022-05-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_shortcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offercategory',
            name='iconImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
