# Generated by Django 4.0.3 on 2022-05-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to=''),
        ),
    ]
