# Generated by Django 3.2.13 on 2022-05-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likestarget',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='likesystem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
