# Generated by Django 3.2.13 on 2022-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_system', '0002_auto_20220529_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesystem',
            name='object_id',
            field=models.CharField(max_length=1024),
        ),
    ]
